package coreJava.streamApi;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class StreamApiDemo {

    private static void filter() {
        List<Integer> numbers = Arrays.asList(1, 2, 3, 4, 5, 6);

        // Using filter to select even numbers
        List<Integer> evens = numbers.stream()
                .filter(n -> n % 2 == 0 && n % 3 == 0)
                .collect(Collectors.toList());

        System.out.println(evens);  // Output: [2, 4, 6]
    }

    private static  void peek() {
        List<String> names = Arrays.asList("john", "jane", "jack");

        // Peeking into the stream to debug
        List <String> list = names.stream()
                .peek(name -> System.out.println("Processing: " + name))
                .map(String::toUpperCase)
                .peek(name -> System.out.println("Processing: " + name))
                .toList();

    }

    private static void mapGroupBy() {
        // Sample Map: Item name -> Quantity
        Map<String, Integer> items = new HashMap<>();
        items.put("Apple", 10);
        items.put("Banana", 20);
        items.put("Orange", 5);
        items.put("Mango", 12);

        // Grouping items based on whether their quantity is >= 10 or not
        Map<Boolean, List<Map.Entry<String, Integer>>> groupedItems = items.entrySet().stream()
                .collect(Collectors.groupingBy(entry -> entry.getValue() >= 10));

        System.out.println("Grouped items:");
        System.out.println(groupedItems);
        System.out.println("Quantity >= 10: " + groupedItems.get(true));
        System.out.println("Quantity < 10: " + groupedItems.get(false));
    }

    private static void sortMap() {
        Map<String, Integer> map = new HashMap<>();
        map.put("apple", 3);
        map.put("banana", 2);
        map.put("cherry", 1);

        // Sort by values in ascending order and collect to LinkedHashMap
        Map<String, Integer> result = map.entrySet().stream()
                .sorted(Map.Entry.comparingByValue())  // Sort by value
                .collect(Collectors.toMap(
                        Map.Entry::getKey,
                        Map.Entry::getValue,
                        (e1,e2) -> e1,
                        LinkedHashMap::new // Use LinkedHashMap to preserve insertion order
                ));

        System.out.println(result);
    }

    static void mapDemo() {
        // making the array list object
        ArrayList<String> fruit = new ArrayList<>();
        fruit.add("Apple");
        fruit.add("mango");
        fruit.add("pineapple");
        fruit.add("kiwi");
        System.out.println("List of fruit-" + fruit);

        // lets use map() to convert list of fruit
        List<Integer> list = fruit.stream()
                .map(String::length)
                .toList();
        System.out.println("List generated by map-" + list);
    }

    static void flatMap() {
        // making the arraylist object of List of Integer
        List<List<Integer>> number = new ArrayList<>();

        // adding the elements to number arraylist
        number.add(Arrays.asList(1, 2));
        number.add(Arrays.asList(3, 4));
        number.add(Arrays.asList(5, 6));
        number.add(Arrays.asList(7, 8));

        System.out.println("List of list-" + number);

        // using flatmap() to flatten this list
        List<Integer> flatList = number.stream()
                .flatMap(Collection::stream)
                .toList();

        // printing the list
        System.out.println("List generate by flatMap-"
                + flatList);
    }

    public static void main(String[] args) {
        mapDemo();
        flatMap();
        sortMap();
        filter();
        peek();
        mapGroupBy();
    }
}
